version: '3.8'

services:
  application:
    container_name: application
    image: swarm-demo
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: "256M"
      #   reservations:
      #     cpus: "0.1"
      #     memory: "128M"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
